### ISSUE TITLE
发邮件的html编辑器里有不少繁体字

### ISSUE THREAD

**Issue by marchtian** [steedos/sogo#1]
![image](https://user-images.githubusercontent.com/7553007/48613573-1c751900-e9c7-11e8-811a-5298b942e161.png)
![image](https://user-images.githubusercontent.com/7553007/48613590-26971780-e9c7-11e8-9687-cccb82058104.png)

**Comment by steedos** [comment]
传入给ck-editor的localeCode应该是 “zh-cn”，现在传入的是 “zh_CN"

**Comment by yinlianghui** [comment]
直接不赋值就行了

**Comment by yinlianghui** [comment]
新版本升级后就坏了
