### ISSUE TITLE
邮件新加中文标签，回车报错

### ISSUE THREAD

**Issue by marchtian** [steedos/sogo#2]
其实是加上了
![image](https://user-images.githubusercontent.com/7553007/48613888-e4220a80-e9c7-11e8-9eaa-5047ccf59c50.png)

**Comment by steedos** [comment]
angular.js:15536 Possibly unhandled rejection: {"data":"","status":501,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/SOGo/so/zhuangjianguo@steedos.cn/Mail/0/folderINBOX/addOrRemoveLabel","data":{"operation":"add","msgUIDs":[4973],"flags":"测试"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","X-XSRF-TOKEN":"233cdd5e656b1e1b0eb3d77438759035183e20ba"}},"statusText":"Request Failed","xhrStatus":"complete"}
(anonymous) @ angular.js:15536
(anonymous) @ angular.js:11815
g @ angular.js:17946
$digest @ angular.js:19075
$apply @ angular.js:19463
k @ angular.js:13312
w @ angular.js:13569
E.onload @ angular.js:13474
load (async)
(anonymous) @ angular.js:13457
s @ angular.js:13257
(anonymous) @ angular.js:12998
(anonymous) @ angular.js:17914
$digest @ angular.js:19075
$apply @ angular.js:19463
(anonymous) @ angular.js:28819
og @ angular.js:3805
d @ angular.js:3793
